In [41]:
import numpy as np

my_list = [2, 3, 4, 2, 3, 4]
arr = np.array(my_list)

print(arr)
print(type(arr))
print(np.__version__)

[2 3 4 2 3 4]
<class 'numpy.ndarray'>
1.24.2


In [15]:
my_tuple = (1, 2, 3, 5)
arr = np.array(my_tuple)
print(arr)
print(type(arr))

[1 2 3 5]
<class 'numpy.ndarray'>


In [29]:
#TYPES OF NDARRAY:

# 0-D Arrays - or Scalars, are the elements in an array. Each value in an array is a 0-D array.
arr = np.array(42)
print(arr)
print(arr.ndim)

42
0


In [28]:
#1-D Arrays - An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.These are the most common and basic arrays.
arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(arr.ndim)

[1 2 3 4 5]
1


In [27]:
#2-D Arrays -An array that has 1-D arrays as its elements is called a 2-D array. These are often used to represent matrix or 2nd order tensors.

arr = np.array([[1, 1, 1], [2, 2, 2]])

print(arr)
print(arr.ndim)

[[1 1 1]
 [2 2 2]]
2


In [26]:
# 3-D arrays - An array that has 2-D arrays (matrices) as its elements is called 3-D array. These are often used to represent a 3rd order tensor.

arr = np.array([[[1, 1, 1], [1, 1, 1]], [[2, 2, 2], [2, 2, 2]], [[3, 3, 3], [3, 3, 3]]])
print(arr)
print(arr.ndim)

[[[1 1 1]
  [1 1 1]]

 [[2 2 2]
  [2 2 2]]

 [[3 3 3]
  [3 3 3]]]
3


In [40]:
# NDIM -  return number of dimensions
# NDMIN - An array can have any number of dimensions.When the array is created, you can define the number of dimensions by using the ndmin argument.
import numpy as np

my_list = [1, 1, 1, 1]
arr = np.array(my_list, ndmin=4)
arr2 = np.array(my_list, ndmin=8)
print(arr)
print(arr2)


[[[[1 1 1 1]]]]
[[[[[[[[1 1 1 1]]]]]]]]


In [44]:
my_list = [10, 20, 30]
arr = np.array(my_list)
print(arr[0])
print(arr[0] + arr[2])

10
40


In [48]:
# INDEXING
#2-D
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0, 4])  # regular list is list[0][0]
print(arr[1, 4])
print(arr.ndim)

5
10
2


In [54]:
# 3-D
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 1])
print(arr[1, 0, 0])
print(arr[-2, -1, -3])

5
7
4


In [75]:
# NumPy Array Slicing
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
print(arr[:-1])
print(arr[1:-1])
print(arr[-3::])
print(arr[1::])
print(arr[-8:-1])
# with step
print(arr[1:8:2])
print(arr[-4::3])



[0 1 2 3 4 5 6]
[1 2 3 4 5 6]
[5 6 7]
[1 2 3 4 5 6 7]
[0 1 2 3 4 5 6]
[1 3 5 7]
[4 7]


In [78]:
# Slicing 2-D Arrays
arr = np.array([[0, 1, 2, 3, 4], [6, 7, 8, 9, 10]])
print(arr[0, 1:5])

# From both elements, return index 2:
print(arr[: 2, 2])

#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
print(arr[0:2, 1:4])

[1 2 3 4]
[2 8]
[[1 2 3]
 [7 8 9]]
